[package]
versioned_files = ["package.json"]
changelog = "CHANGELOG.md"

[github]
owner = "SiaFoundation"
repo = "sia-storage-js"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git switch -c release"

[[workflows.steps]]
type = "PrepareRelease"
ignore_conventional_commits = true

[[workflows.steps]]
type = "Command"
command = "bun run scripts/sync-versions.ts"

[[workflows.steps]]
type = "Command"
command = "git add -A"

[[workflows.steps]]
type = "Command"
command = "git commit -m 'chore: release'"

[[workflows.steps]]
type = "Command"
command = "git push --force --set-upstream origin release"

[[workflows.steps]]
type = "Command"
command = "bun scripts/create-release-pr.ts"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"
